# Generated by Django 6.0.1 on 2026-03-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название игры')),
                ('version', models.CharField(max_length=30, verbose_name='Версия')),
                ('developer', models.CharField(max_length=255, verbose_name='Разработчик')),
                ('release_date', models.CharField(max_length=100, verbose_name='Дата выпуска')),
                ('min_requirements', models.TextField(verbose_name='Минимальные системные требования')),
                ('rec_requirements', models.TextField(verbose_name='Рекомендуемые системные требования')),
                ('description', models.TextField(verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('genres', models.ManyToManyField(related_name='games', to='games.genre', verbose_name='Жанры')),
                ('interface_language', models.ManyToManyField(related_name='games_interface', to='games.language', verbose_name='Язык интерфейса')),
                ('voice_language', models.ManyToManyField(related_name='games_voice', to='games.language', verbose_name='Язык озвучивания')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['-created_at'],
            },
        ),
    ]
