# Generated by Django 6.0.1 on 2026-03-05 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_favoritegame'),
        ('games', '0002_game_download_link'),
    ]

    operations = [
    ]
