# Generated by Django 6.0 on 2026-02-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='news_commen_news_id_fd2ae8_idx',
            old_name='news_comment_news_created_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='news_commen_parent__f18116_idx',
            old_name='news_comment_parent_idx',
        ),
        migrations.RenameIndex(
            model_name='news',
            new_name='news_news_created_33ef44_idx',
            old_name='news_news_created_idx',
        ),
        migrations.RenameIndex(
            model_name='news',
            new_name='news_news_categor_5f9b52_idx',
            old_name='news_news_category_idx',
        ),
        migrations.RenameIndex(
            model_name='news',
            new_name='news_news_is_publ_075179_idx',
            old_name='news_news_is_publ_idx',
        ),
        migrations.RenameIndex(
            model_name='newsfavorite',
            new_name='news_newsfa_user_id_b189bf_idx',
            old_name='news_newsfav_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='newslike',
            new_name='news_newsli_news_id_deadef_idx',
            old_name='news_newslik_news_user_idx',
        ),
    ]
