# Generated by Django 6.0 on 2026-02-17 10:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Введите ваш email', max_length=254, unique=True, verbose_name='Email')),
                ('is_moderator', models.BooleanField(default=False, help_text='Пользователь имеет права модератора', verbose_name='Модератор')),
                ('can_create_news', models.BooleanField(default=False, verbose_name='Может создавать новости')),
                ('can_edit_news', models.BooleanField(default=False, verbose_name='Может редактировать новости')),
                ('can_delete_news', models.BooleanField(default=False, verbose_name='Может удалять новости')),
                ('can_delete_comments', models.BooleanField(default=False, verbose_name='Может удалять комментарии')),
                ('can_ban_1_day', models.BooleanField(default=False, verbose_name='Может банить на один день')),
                ('last_activity', models.DateTimeField(blank=True, help_text='Дата и время последней активности на сайте', null=True, verbose_name='Последняя активность')),
                ('appointed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_moderators', to=settings.AUTH_USER_MODEL, verbose_name='Назначен администратором')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_ban', models.BooleanField(default=True, verbose_name='Может выдавать баны')),
                ('can_manage_moderators', models.BooleanField(default=True, verbose_name='Может управлять модераторами')),
                ('can_view_statistics', models.BooleanField(default=True, verbose_name='Может просматривать статистику')),
                ('manage_moderators', models.ManyToManyField(blank=True, limit_choices_to={'is_moderator': True}, related_name='managed_by_admin', to=settings.AUTH_USER_MODEL, verbose_name='Назначенные модераторы')),
                ('user', models.OneToOneField(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='Админ')),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(limit_choices_to=models.Q(('is_moderator', True), ('is_superuser', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
                'permissions': [('can_create_news', 'Может создавать новости')],
            },
        ),
    ]
