# Generated by Django 6.0 on 2026-02-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Username в Telegram'),
        ),
    ]
