# Generated by Django 6.0.1 on 2026-02-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_username_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID пользователя в Telegram'),
        ),
    ]
