# Generated by Django 6.0.1 on 2026-03-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_tg_username_id'),
        ('core', '0004_user_telegram_chat_id'),
    ]

    operations = [
    ]
