# Generated by Django 6.0.1 on 2026-03-02 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20260302_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tg_username_id',
        ),
    ]
