# Generated by Django 6.0.1 on 2026-02-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='torrentdownload',
            new_name='torrents_to_user_id_1899fd_idx',
            old_name='torrents_to_user_started_idx',
        ),
        migrations.RenameIndex(
            model_name='torrentdownload',
            new_name='torrents_to_torrent_d48674_idx',
            old_name='torrents_to_torrent_status_idx',
        ),
        migrations.RenameIndex(
            model_name='torrentfile',
            new_name='torrents_to_created_3d5a7d_idx',
            old_name='torrents_to_created_idx',
        ),
        migrations.RenameIndex(
            model_name='torrentfile',
            new_name='torrents_to_status_a165fb_idx',
            old_name='torrents_to_status_idx',
        ),
        migrations.RenameIndex(
            model_name='torrentfile',
            new_name='torrents_to_news_id_2f0571_idx',
            old_name='torrents_to_news_idx',
        ),
    ]
