# Generated by Django 6.0.1 on 2026-02-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_05b4bc_idx',
            old_name='notificatio_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_status_d92267_idx',
            old_name='notificatio_status_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_type_co_4a3e1e_idx',
            old_name='notificatio_type_code_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationsubscription',
            new_name='notificatio_user_id_485618_idx',
            old_name='notificatio_user_is_active_idx',
        ),
    ]
